# Generated by Django 5.0.1 on 2024-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=255)),
                ('is_deleted', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.TextField()),
                ('category_id', models.IntegerField()),
                ('description', models.TextField()),
                ('is_deleted', models.IntegerField()),
                ('bg_color', models.CharField(max_length=255)),
                ('html', models.TextField(default=None)),
            ],
        ),
    ]
